<?php

use Illuminate\Database\Seeder;

class PaisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
    }

    public static $arrayPaises = [
        array("id" =>1, "codigo" =>"ABW", "pais" => "Aruba", "continente" => "North America", "poblacion" =>103000),
        array("id" =>2, "codigo" =>"AFG", "pais" => "Afghanistan", "continente" => "Asia", "poblacion" =>22720000),
        array("id" =>3, "codigo" =>"AGO", "pais" => "Angola", "continente" => "Africa", "poblacion" =>12878000),
        array("id" =>4, "codigo" =>"AIA", "pais" => "Anguilla", "continente" => "North America", "poblacion" =>8000),
        array("id" =>5, "codigo" =>"ALB", "pais" => "Albania", "continente" => "Europe", "poblacion" =>3401200),
        array("id" =>6, "codigo" =>"AND", "pais" => "Andorra", "continente" => "Europe", "poblacion" =>78000),
        array("id" =>7, "codigo" =>"ANT", "pais" => "Netherlands Antilles", "continente" => "North America", "poblacion" =>217000),
        array("id" =>8, "codigo" =>"ARE", "pais" => "United Arab Emirates", "continente" => "Asia", "poblacion" =>2441000),
        array("id" =>9, "codigo" =>"ARG", "pais" => "Argentina", "continente" => "South America", "poblacion" =>37032000),
        array("id" =>10, "codigo" =>"ARM", "pais" => "Armenia", "continente" => "Asia", "poblacion" =>3520000),
        array("id" =>11, "codigo" =>"ASM", "pais" => "American Samoa", "continente" => "Oceania", "poblacion" =>68000),
        array("id" =>12, "codigo" =>"ATA", "pais" => "Antarctica", "continente" => "Antarctica", "poblacion" =>0),
        array("id" =>13, "codigo" =>"ATF", "pais" => "French Southern territories", "continente" => "Antarctica", "poblacion" =>0),
        array("id" =>14, "codigo" =>"ATG", "pais" => "Antigua and Barbuda", "continente" => "North America", "poblacion" =>68000),
        array("id" =>15, "codigo" =>"AUS", "pais" => "Australia", "continente" => "Oceania", "poblacion" =>18886000),
        array("id" =>16, "codigo" =>"AUT", "pais" => "Austria", "continente" => "Europe", "poblacion" =>8091800),
        array("id" =>17, "codigo" =>"AZE", "pais" => "Azerbaijan", "continente" => "Asia", "poblacion" =>7734000),
        array("id" =>18, "codigo" =>"BDI", "pais" => "Burundi", "continente" => "Africa", "poblacion" =>6695000),
        array("id" =>19, "codigo" =>"BEL", "pais" => "Belgium", "continente" => "Europe", "poblacion" =>10239000),
        array("id" =>20, "codigo" =>"BEN", "pais" => "Benin", "continente" => "Africa", "poblacion" =>6097000),
        array("id" =>21, "codigo" =>"BFA", "pais" => "Burkina Faso", "continente" => "Africa", "poblacion" =>11937000),
        array("id" =>22, "codigo" =>"BGD", "pais" => "Bangladesh", "continente" => "Asia", "poblacion" =>129155000),
        array("id" =>23, "codigo" =>"BGR", "pais" => "Bulgaria", "continente" => "Europe", "poblacion" =>8190900),
        array("id" =>24, "codigo" =>"BHR", "pais" => "Bahrain", "continente" => "Asia", "poblacion" =>617000),
        array("id" =>25, "codigo" =>"BHS", "pais" => "Bahamas", "continente" => "North America", "poblacion" =>307000),
        array("id" =>26, "codigo" =>"BIH", "pais" => "Bosnia and Herzegovina", "continente" => "Europe", "poblacion" =>3972000),
        array("id" =>27, "codigo" =>"BLR", "pais" => "Belarus", "continente" => "Europe", "poblacion" =>10236000),
        array("id" =>28, "codigo" =>"BLZ", "pais" => "Belize", "continente" => "North America", "poblacion" =>241000),
        array("id" =>29, "codigo" =>"BMU", "pais" => "Bermuda", "continente" => "North America", "poblacion" =>65000),
        array("id" =>30, "codigo" =>"BOL", "pais" => "Bolivia", "continente" => "South America", "poblacion" =>8329000),
        array("id" =>31, "codigo" =>"BRA", "pais" => "Brazil", "continente" => "South America", "poblacion" =>170115000),
        array("id" =>32, "codigo" =>"BRB", "pais" => "Barbados", "continente" => "North America", "poblacion" =>270000),
        array("id" =>33, "codigo" =>"BRN", "pais" => "Brunei", "continente" => "Asia", "poblacion" =>328000),
        array("id" =>34, "codigo" =>"BTN", "pais" => "Bhutan", "continente" => "Asia", "poblacion" =>2124000),
        array("id" =>35, "codigo" =>"BVT", "pais" => "Bouvet Island", "continente" => "Antarctica", "poblacion" =>0),
        array("id" =>36, "codigo" =>"BWA", "pais" => "Botswana", "continente" => "Africa", "poblacion" =>1622000),
        array("id" =>37, "codigo" =>"CAF", "pais" => "Central African Republic", "continente" => "Africa", "poblacion" =>3615000),
        array("id" =>38, "codigo" =>"CAN", "pais" => "Canada", "continente" => "North America", "poblacion" =>31147000),
        array("id" =>39, "codigo" =>"CCK", "pais" => "Cocos (Keeling) Islands", "continente" => "Oceania", "poblacion" =>600),
        array("id" =>40, "codigo" =>"CHE", "pais" => "Switzerland", "continente" => "Europe", "poblacion" =>7160400),
        array("id" =>41, "codigo" =>"CHL", "pais" => "Chile", "continente" => "South America", "poblacion" =>15211000),
        array("id" =>42, "codigo" =>"CHN", "pais" => "China", "continente" => "Asia", "poblacion" =>1277558000),
        array("id" =>43, "codigo" =>"CIV", "pais" => "Côte d'Ivoire", "continente" => "Africa", "poblacion" =>14786000),
        array("id" =>44, "codigo" =>"CMR", "pais" => "Cameroon", "continente" => "Africa", "poblacion" =>15085000),
        array("id" =>45, "codigo" =>"COD", "pais" => "Congo, The Democratic Republic of the", "continente" => "Africa", "poblacion" =>51654000),
        array("id" =>46, "codigo" =>"COG", "pais" => "Congo", "continente" => "Africa", "poblacion" =>2943000),
        array("id" =>47, "codigo" =>"COK", "pais" => "Cook Islands", "continente" => "Oceania", "poblacion" =>20000),
        array("id" =>48, "codigo" =>"COL", "pais" => "Colombia", "continente" => "South America", "poblacion" =>42321000),
        array("id" =>49, "codigo" =>"COM", "pais" => "Comoros", "continente" => "Africa", "poblacion" =>578000),
        array("id" =>50, "codigo" =>"CPV", "pais" => "Cape Verde", "continente" => "Africa", "poblacion" =>428000),
        array("id" =>51, "codigo" =>"CRI", "pais" => "Costa Rica", "continente" => "North America", "poblacion" =>4023000),
        array("id" =>52, "codigo" =>"CUB", "pais" => "Cuba", "continente" => "North America", "poblacion" =>11201000),
        array("id" =>53, "codigo" =>"CXR", "pais" => "Christmas Island", "continente" => "Oceania", "poblacion" =>2500),
        array("id" =>54, "codigo" =>"CYM", "pais" => "Cayman Islands", "continente" => "North America", "poblacion" =>38000),
        array("id" =>55, "codigo" =>"CYP", "pais" => "Cyprus", "continente" => "Asia", "poblacion" =>754700),
        array("id" =>56, "codigo" =>"CZE", "pais" => "Czech Republic", "continente" => "Europe", "poblacion" =>10278100),
        array("id" =>57, "codigo" =>"DEU", "pais" => "Germany", "continente" => "Europe", "poblacion" =>82164700),
        array("id" =>58, "codigo" =>"DJI", "pais" => "Djibouti", "continente" => "Africa", "poblacion" =>638000),
        array("id" =>59, "codigo" =>"DMA", "pais" => "Dominica", "continente" => "North America", "poblacion" =>71000),
        array("id" =>60, "codigo" =>"DNK", "pais" => "Denmark", "continente" => "Europe", "poblacion" =>5330000),
        array("id" =>61, "codigo" =>"DOM", "pais" => "Dominican Republic", "continente" => "North America", "poblacion" =>8495000),
        array("id" =>62, "codigo" =>"DZA", "pais" => "Algeria", "continente" => "Africa", "poblacion" =>31471000),
        array("id" =>63, "codigo" =>"ECU", "pais" => "Ecuador", "continente" => "South America", "poblacion" =>12646000),
        array("id" =>64, "codigo" =>"EGY", "pais" => "Egypt", "continente" => "Africa", "poblacion" =>68470000),
        array("id" =>65, "codigo" =>"ERI", "pais" => "Eritrea", "continente" => "Africa", "poblacion" =>3850000),
        array("id" =>66, "codigo" =>"ESH", "pais" => "Western Sahara", "continente" => "Africa", "poblacion" =>293000),
        array("id" =>67, "codigo" =>"ESP", "pais" => "Spain", "continente" => "Europe", "poblacion" =>39441700),
        array("id" =>68, "codigo" =>"EST", "pais" => "Estonia", "continente" => "Europe", "poblacion" =>1439200),
        array("id" =>69, "codigo" =>"ETH", "pais" => "Ethiopia", "continente" => "Africa", "poblacion" =>62565000),
        array("id" =>70, "codigo" =>"FIN", "pais" => "Finland", "continente" => "Europe", "poblacion" =>5171300),
        array("id" =>71, "codigo" =>"FJI", "pais" => "Fiji Islands", "continente" => "Oceania", "poblacion" =>817000),
        array("id" =>72, "codigo" =>"FLK", "pais" => "Falkland Islands", "continente" => "South America", "poblacion" =>2000),
        array("id" =>73, "codigo" =>"FRA", "pais" => "France", "continente" => "Europe", "poblacion" =>59225700),
        array("id" =>74, "codigo" =>"FRO", "pais" => "Faroe Islands", "continente" => "Europe", "poblacion" =>43000),
        array("id" =>75, "codigo" =>"FSM", "pais" => "Micronesia, Federated States of", "continente" => "Oceania", "poblacion" =>119000),
        array("id" =>76, "codigo" =>"GAB", "pais" => "Gabon", "continente" => "Africa", "poblacion" =>1226000),
        array("id" =>77, "codigo" =>"GBR", "pais" => "United Kingdom", "continente" => "Europe", "poblacion" =>59623400),
        array("id" =>78, "codigo" =>"GEO", "pais" => "Georgia", "continente" => "Asia", "poblacion" =>4968000),
        array("id" =>79, "codigo" =>"GHA", "pais" => "Ghana", "continente" => "Africa", "poblacion" =>20212000),
        array("id" =>80, "codigo" =>"GIB", "pais" => "Gibraltar", "continente" => "Europe", "poblacion" =>25000),
        array("id" =>81, "codigo" =>"GIN", "pais" => "Guinea", "continente" => "Africa", "poblacion" =>7430000),
        array("id" =>82, "codigo" =>"GLP", "pais" => "Guadeloupe", "continente" => "North America", "poblacion" =>456000),
        array("id" =>83, "codigo" =>"GMB", "pais" => "Gambia", "continente" => "Africa", "poblacion" =>1305000),
        array("id" =>84, "codigo" =>"GNB", "pais" => "Guinea-Bissau", "continente" => "Africa", "poblacion" =>1213000),
        array("id" =>85, "codigo" =>"GNQ", "pais" => "Equatorial Guinea", "continente" => "Africa", "poblacion" =>453000),
        array("id" =>86, "codigo" =>"GRC", "pais" => "Greece", "continente" => "Europe", "poblacion" =>10545700),
        array("id" =>87, "codigo" =>"GRD", "pais" => "Grenada", "continente" => "North America", "poblacion" =>94000),
        array("id" =>88, "codigo" =>"GRL", "pais" => "Greenland", "continente" => "North America", "poblacion" =>56000),
        array("id" =>89, "codigo" =>"GTM", "pais" => "Guatemala", "continente" => "North America", "poblacion" =>11385000),
        array("id" =>90, "codigo" =>"GUF", "pais" => "French Guiana", "continente" => "South America", "poblacion" =>181000),
        array("id" =>91, "codigo" =>"GUM", "pais" => "Guam", "continente" => "Oceania", "poblacion" =>168000),
        array("id" =>92, "codigo" =>"GUY", "pais" => "Guyana", "continente" => "South America", "poblacion" =>861000),
        array("id" =>93, "codigo" =>"HKG", "pais" => "Hong Kong", "continente" => "Asia", "poblacion" =>6782000),
        array("id" =>94, "codigo" =>"HMD", "pais" => "Heard Island and McDonald Islands", "continente" => "Antarctica", "poblacion" =>0),
        array("id" =>95, "codigo" =>"HND", "pais" => "Honduras", "continente" => "North America", "poblacion" =>6485000),
        array("id" =>96, "codigo" =>"HRV", "pais" => "Croatia", "continente" => "Europe", "poblacion" =>4473000),
        array("id" =>97, "codigo" =>"HTI", "pais" => "Haiti", "continente" => "North America", "poblacion" =>8222000),
        array("id" =>98, "codigo" =>"HUN", "pais" => "Hungary", "continente" => "Europe", "poblacion" =>10043200),
        array("id" =>99, "codigo" =>"IDN", "pais" => "Indonesia", "continente" => "Asia", "poblacion" =>212107000),
        array("id" =>100, "codigo" =>"IND", "pais" => "India", "continente" => "Asia", "poblacion" =>1013662000),
        array("id" =>101, "codigo" =>"IOT", "pais" => "British Indian Ocean Territory", "continente" => "Africa", "poblacion" =>0),
        array("id" =>102, "codigo" =>"IRL", "pais" => "Ireland", "continente" => "Europe", "poblacion" =>3775100),
        array("id" =>103, "codigo" =>"IRN", "pais" => "Iran", "continente" => "Asia", "poblacion" =>67702000),
        array("id" =>104, "codigo" =>"IRQ", "pais" => "Iraq", "continente" => "Asia", "poblacion" =>23115000),
        array("id" =>105, "codigo" =>"ISL", "pais" => "Iceland", "continente" => "Europe", "poblacion" =>279000),
        array("id" =>106, "codigo" =>"ISR", "pais" => "Israel", "continente" => "Asia", "poblacion" =>6217000),
        array("id" =>107, "codigo" =>"ITA", "pais" => "Italy", "continente" => "Europe", "poblacion" =>57680000),
        array("id" =>108, "codigo" =>"JAM", "pais" => "Jamaica", "continente" => "North America", "poblacion" =>2583000),
        array("id" =>109, "codigo" =>"JOR", "pais" => "Jordan", "continente" => "Asia", "poblacion" =>5083000),
        array("id" =>110, "codigo" =>"JPN", "pais" => "Japan", "continente" => "Asia", "poblacion" =>126714000),
        array("id" =>111, "codigo" =>"KAZ", "pais" => "Kazakstan", "continente" => "Asia", "poblacion" =>16223000),
        array("id" =>112, "codigo" =>"KEN", "pais" => "Kenya", "continente" => "Africa", "poblacion" =>30080000),
        array("id" =>113, "codigo" =>"KGZ", "pais" => "Kyrgyzstan", "continente" => "Asia", "poblacion" =>4699000),
        array("id" =>114, "codigo" =>"KHM", "pais" => "Cambodia", "continente" => "Asia", "poblacion" =>11168000),
        array("id" =>115, "codigo" =>"KIR", "pais" => "Kiribati", "continente" => "Oceania", "poblacion" =>83000),
        array("id" =>116, "codigo" =>"KNA", "pais" => "Saint Kitts and Nevis", "continente" => "North America", "poblacion" =>38000),
        array("id" =>117, "codigo" =>"KOR", "pais" => "South Korea", "continente" => "Asia", "poblacion" =>46844000),
        array("id" =>118, "codigo" =>"KWT", "pais" => "Kuwait", "continente" => "Asia", "poblacion" =>1972000),
        array("id" =>119, "codigo" =>"LAO", "pais" => "Laos", "continente" => "Asia", "poblacion" =>5433000),
        array("id" =>120, "codigo" =>"LBN", "pais" => "Lebanon", "continente" => "Asia", "poblacion" =>3282000),
        array("id" =>121, "codigo" =>"LBR", "pais" => "Liberia", "continente" => "Africa", "poblacion" =>3154000),
        array("id" =>122, "codigo" =>"LBY", "pais" => "Libyan Arab Jamahiriya", "continente" => "Africa", "poblacion" =>5605000),
        array("id" =>123, "codigo" =>"LCA", "pais" => "Saint Lucia", "continente" => "North America", "poblacion" =>154000),
        array("id" =>124, "codigo" =>"LIE", "pais" => "Liechtenstein", "continente" => "Europe", "poblacion" =>32300),
        array("id" =>125, "codigo" =>"LKA", "pais" => "Sri Lanka", "continente" => "Asia", "poblacion" =>18827000),
        array("id" =>126, "codigo" =>"LSO", "pais" => "Lesotho", "continente" => "Africa", "poblacion" =>2153000),
        array("id" =>127, "codigo" =>"LTU", "pais" => "Lithuania", "continente" => "Europe", "poblacion" =>3698500),
        array("id" =>128, "codigo" =>"LUX", "pais" => "Luxembourg", "continente" => "Europe", "poblacion" =>435700),
        array("id" =>129, "codigo" =>"LVA", "pais" => "Latvia", "continente" => "Europe", "poblacion" =>2424200),
        array("id" =>130, "codigo" =>"MAC", "pais" => "Macao", "continente" => "Asia", "poblacion" =>473000),
        array("id" =>131, "codigo" =>"MAR", "pais" => "Morocco", "continente" => "Africa", "poblacion" =>28351000),
        array("id" =>132, "codigo" =>"MCO", "pais" => "Monaco", "continente" => "Europe", "poblacion" =>34000),
        array("id" =>133, "codigo" =>"MDA", "pais" => "Moldova", "continente" => "Europe", "poblacion" =>4380000),
        array("id" =>134, "codigo" =>"MDG", "pais" => "Madagascar", "continente" => "Africa", "poblacion" =>15942000),
        array("id" =>135, "codigo" =>"MDV", "pais" => "Maldives", "continente" => "Asia", "poblacion" =>286000),
        array("id" =>136, "codigo" =>"MEX", "pais" => "Mexico", "continente" => "North America", "poblacion" =>98881000),
        array("id" =>137, "codigo" =>"MHL", "pais" => "Marshall Islands", "continente" => "Oceania", "poblacion" =>64000),
        array("id" =>138, "codigo" =>"MKD", "pais" => "Macedonia", "continente" => "Europe", "poblacion" =>2024000),
        array("id" =>139, "codigo" =>"MLI", "pais" => "Mali", "continente" => "Africa", "poblacion" =>11234000),
        array("id" =>140, "codigo" =>"MLT", "pais" => "Malta", "continente" => "Europe", "poblacion" =>380200),
        array("id" =>141, "codigo" =>"MMR", "pais" => "Myanmar", "continente" => "Asia", "poblacion" =>45611000),
        array("id" =>142, "codigo" =>"MNG", "pais" => "Mongolia", "continente" => "Asia", "poblacion" =>2662000),
        array("id" =>143, "codigo" =>"MNP", "pais" => "Northern Mariana Islands", "continente" => "Oceania", "poblacion" =>78000),
        array("id" =>144, "codigo" =>"MOZ", "pais" => "Mozambique", "continente" => "Africa", "poblacion" =>19680000),
        array("id" =>145, "codigo" =>"MRT", "pais" => "Mauritania", "continente" => "Africa", "poblacion" =>2670000),
        array("id" =>146, "codigo" =>"MSR", "pais" => "Montserrat", "continente" => "North America", "poblacion" =>11000),
        array("id" =>147, "codigo" =>"MTQ", "pais" => "Martinique", "continente" => "North America", "poblacion" =>395000),
        array("id" =>148, "codigo" =>"MUS", "pais" => "Mauritius", "continente" => "Africa", "poblacion" =>1158000),
        array("id" =>149, "codigo" =>"MWI", "pais" => "Malawi", "continente" => "Africa", "poblacion" =>10925000),
        array("id" =>150, "codigo" =>"MYS", "pais" => "Malaysia", "continente" => "Asia", "poblacion" =>22244000),
        array("id" =>151, "codigo" =>"MYT", "pais" => "Mayotte", "continente" => "Africa", "poblacion" =>149000),
        array("id" =>152, "codigo" =>"NAM", "pais" => "Namibia", "continente" => "Africa", "poblacion" =>1726000),
        array("id" =>153, "codigo" =>"NCL", "pais" => "New Caledonia", "continente" => "Oceania", "poblacion" =>214000),
        array("id" =>154, "codigo" =>"NER", "pais" => "Niger", "continente" => "Africa", "poblacion" =>10730000),
        array("id" =>155, "codigo" =>"NFK", "pais" => "Norfolk Island", "continente" => "Oceania", "poblacion" =>2000),
        array("id" =>156, "codigo" =>"NGA", "pais" => "Nigeria", "continente" => "Africa", "poblacion" =>111506000),
        array("id" =>157, "codigo" =>"NIC", "pais" => "Nicaragua", "continente" => "North America", "poblacion" =>5074000),
        array("id" =>158, "codigo" =>"NIU", "pais" => "Niue", "continente" => "Oceania", "poblacion" =>2000),
        array("id" =>159, "codigo" =>"NLD", "pais" => "Netherlands", "continente" => "Europe", "poblacion" =>15864000),
        array("id" =>160, "codigo" =>"NOR", "pais" => "Norway", "continente" => "Europe", "poblacion" =>4478500),
        array("id" =>161, "codigo" =>"NPL", "pais" => "Nepal", "continente" => "Asia", "poblacion" =>23930000),
        array("id" =>162, "codigo" =>"NRU", "pais" => "Nauru", "continente" => "Oceania", "poblacion" =>12000),
        array("id" =>163, "codigo" =>"NZL", "pais" => "New Zealand", "continente" => "Oceania", "poblacion" =>3862000),
        array("id" =>164, "codigo" =>"OMN", "pais" => "Oman", "continente" => "Asia", "poblacion" =>2542000),
        array("id" =>165, "codigo" =>"PAK", "pais" => "Pakistan", "continente" => "Asia", "poblacion" =>156483000),
        array("id" =>166, "codigo" =>"PAN", "pais" => "Panama", "continente" => "North America", "poblacion" =>2856000),
        array("id" =>167, "codigo" =>"PCN", "pais" => "Pitcairn", "continente" => "Oceania", "poblacion" =>50),
        array("id" =>168, "codigo" =>"PER", "pais" => "Peru", "continente" => "South America", "poblacion" =>25662000),
        array("id" =>169, "codigo" =>"PHL", "pais" => "Philippines", "continente" => "Asia", "poblacion" =>75967000),
        array("id" =>170, "codigo" =>"PLW", "pais" => "Palau", "continente" => "Oceania", "poblacion" =>19000),
        array("id" =>171, "codigo" =>"PNG", "pais" => "Papua New Guinea", "continente" => "Oceania", "poblacion" =>4807000),
        array("id" =>172, "codigo" =>"POL", "pais" => "Poland", "continente" => "Europe", "poblacion" =>38653600),
        array("id" =>173, "codigo" =>"PRI", "pais" => "Puerto Rico", "continente" => "North America", "poblacion" =>3869000),
        array("id" =>174, "codigo" =>"PRK", "pais" => "North Korea", "continente" => "Asia", "poblacion" =>24039000),
        array("id" =>175, "codigo" =>"PRT", "pais" => "Portugal", "continente" => "Europe", "poblacion" =>9997600),
        array("id" =>176, "codigo" =>"PRY", "pais" => "Paraguay", "continente" => "South America", "poblacion" =>5496000),
        array("id" =>177, "codigo" =>"PSE", "pais" => "Palestine", "continente" => "Asia", "poblacion" =>3101000),
        array("id" =>178, "codigo" =>"PYF", "pais" => "French Polynesia", "continente" => "Oceania", "poblacion" =>235000),
        array("id" =>179, "codigo" =>"QAT", "pais" => "Qatar", "continente" => "Asia", "poblacion" =>599000),
        array("id" =>180, "codigo" =>"REU", "pais" => "Réunion", "continente" => "Africa", "poblacion" =>699000),
        array("id" =>181, "codigo" =>"ROM", "pais" => "Romania", "continente" => "Europe", "poblacion" =>22455500),
        array("id" =>182, "codigo" =>"RUS", "pais" => "Russian Federation", "continente" => "Europe", "poblacion" =>146934000),
        array("id" =>183, "codigo" =>"RWA", "pais" => "Rwanda", "continente" => "Africa", "poblacion" =>7733000),
        array("id" =>184, "codigo" =>"SAU", "pais" => "Saudi Arabia", "continente" => "Asia", "poblacion" =>21607000),
        array("id" =>185, "codigo" =>"SDN", "pais" => "Sudan", "continente" => "Africa", "poblacion" =>29490000),
        array("id" =>186, "codigo" =>"SEN", "pais" => "Senegal", "continente" => "Africa", "poblacion" =>9481000),
        array("id" =>187, "codigo" =>"SGP", "pais" => "Singapore", "continente" => "Asia", "poblacion" =>3567000),
        array("id" =>188, "codigo" =>"SGS", "pais" => "South Georgia and the South Sandwich Islands", "continente" => "Antarctica", "poblacion" =>0),
        array("id" =>189, "codigo" =>"SHN", "pais" => "Saint Helena", "continente" => "Africa", "poblacion" =>6000),
        array("id" =>190, "codigo" =>"SJM", "pais" => "Svalbard and Jan Mayen", "continente" => "Europe", "poblacion" =>3200),
        array("id" =>191, "codigo" =>"SLB", "pais" => "Solomon Islands", "continente" => "Oceania", "poblacion" =>444000),
        array("id" =>192, "codigo" =>"SLE", "pais" => "Sierra Leone", "continente" => "Africa", "poblacion" =>4854000),
        array("id" =>193, "codigo" =>"SLV", "pais" => "El Salvador", "continente" => "North America", "poblacion" =>6276000),
        array("id" =>194, "codigo" =>"SMR", "pais" => "San Marino", "continente" => "Europe", "poblacion" =>27000),
        array("id" =>195, "codigo" =>"SOM", "pais" => "Somalia", "continente" => "Africa", "poblacion" =>10097000),
        array("id" =>196, "codigo" =>"SPM", "pais" => "Saint Pierre and Miquelon", "continente" => "North America", "poblacion" =>7000),
        array("id" =>197, "codigo" =>"STP", "pais" => "Sao Tome and Principe", "continente" => "Africa", "poblacion" =>147000),
        array("id" =>198, "codigo" =>"SUR", "pais" => "Suriname", "continente" => "South America", "poblacion" =>417000),
        array("id" =>199, "codigo" =>"SVK", "pais" => "Slovakia", "continente" => "Europe", "poblacion" =>5398700),
        array("id" =>200, "codigo" =>"SVN", "pais" => "Slovenia", "continente" => "Europe", "poblacion" =>1987800),
        array("id" =>201, "codigo" =>"SWE", "pais" => "Sweden", "continente" => "Europe", "poblacion" =>8861400),
        array("id" =>202, "codigo" =>"SWZ", "pais" => "Swaziland", "continente" => "Africa", "poblacion" =>1008000),
        array("id" =>203, "codigo" =>"SYC", "pais" => "Seychelles", "continente" => "Africa", "poblacion" =>77000),
        array("id" =>204, "codigo" =>"SYR", "pais" => "Syria", "continente" => "Asia", "poblacion" =>16125000),
        array("id" =>205, "codigo" =>"TCA", "pais" => "Turks and Caicos Islands", "continente" => "North America", "poblacion" =>17000),
        array("id" =>206, "codigo" =>"TCD", "pais" => "Chad", "continente" => "Africa", "poblacion" =>7651000),
        array("id" =>207, "codigo" =>"TGO", "pais" => "Togo", "continente" => "Africa", "poblacion" =>4629000),
        array("id" =>208, "codigo" =>"THA", "pais" => "Thailand", "continente" => "Asia", "poblacion" =>61399000),
        array("id" =>209, "codigo" =>"TJK", "pais" => "Tajikistan", "continente" => "Asia", "poblacion" =>6188000),
        array("id" =>210, "codigo" =>"TKL", "pais" => "Tokelau", "continente" => "Oceania", "poblacion" =>2000),
        array("id" =>211, "codigo" =>"TKM", "pais" => "Turkmenistan", "continente" => "Asia", "poblacion" =>4459000),
        array("id" =>212, "codigo" =>"TMP", "pais" => "East Timor", "continente" => "Asia", "poblacion" =>885000),
        array("id" =>213, "codigo" =>"TON", "pais" => "Tonga", "continente" => "Oceania", "poblacion" =>99000),
        array("id" =>214, "codigo" =>"TTO", "pais" => "Trinidad and Tobago", "continente" => "North America", "poblacion" =>1295000),
        array("id" =>215, "codigo" =>"TUN", "pais" => "Tunisia", "continente" => "Africa", "poblacion" =>9586000),
        array("id" =>216, "codigo" =>"TUR", "pais" => "Turkey", "continente" => "Asia", "poblacion" =>66591000),
        array("id" =>217, "codigo" =>"TUV", "pais" => "Tuvalu", "continente" => "Oceania", "poblacion" =>12000),
        array("id" =>218, "codigo" =>"TWN", "pais" => "Taiwan", "continente" => "Asia", "poblacion" =>22256000),
        array("id" =>219, "codigo" =>"TZA", "pais" => "Tanzania", "continente" => "Africa", "poblacion" =>33517000),
        array("id" =>220, "codigo" =>"UGA", "pais" => "Uganda", "continente" => "Africa", "poblacion" =>21778000),
        array("id" =>221, "codigo" =>"UKR", "pais" => "Ukraine", "continente" => "Europe", "poblacion" =>50456000),
        array("id" =>222, "codigo" =>"UMI", "pais" => "United States Minor Outlying Islands", "continente" => "Oceania", "poblacion" =>0),
        array("id" =>223, "codigo" =>"URY", "pais" => "Uruguay", "continente" => "South America", "poblacion" =>3337000),
        array("id" =>224, "codigo" =>"USA", "pais" => "United States", "continente" => "North America", "poblacion" =>278357000),
        array("id" =>225, "codigo" =>"UZB", "pais" => "Uzbekistan", "continente" => "Asia", "poblacion" =>24318000),
        array("id" =>226, "codigo" =>"VAT", "pais" => "Holy See (Vatican City State)", "continente" => "Europe", "poblacion" =>1000),
        array("id" =>227, "codigo" =>"VCT", "pais" => "Saint Vincent and the Grenadines", "continente" => "North America", "poblacion" =>114000),
        array("id" =>228, "codigo" =>"VEN", "pais" => "Venezuela", "continente" => "South America", "poblacion" =>24170000),
        array("id" =>229, "codigo" =>"VGB", "pais" => "Virgin Islands, British", "continente" => "North America", "poblacion" =>21000),
        array("id" =>230, "codigo" =>"VIR", "pais" => "Virgin Islands, U.S.", "continente" => "North America", "poblacion" =>93000),
        array("id" =>231, "codigo" =>"VNM", "pais" => "Vietnam", "continente" => "Asia", "poblacion" =>79832000),
        array("id" =>232, "codigo" =>"VUT", "pais" => "Vanuatu", "continente" => "Oceania", "poblacion" =>190000),
        array("id" =>233, "codigo" =>"WLF", "pais" => "Wallis and Futuna", "continente" => "Oceania", "poblacion" =>15000),
        array("id" =>234, "codigo" =>"WSM", "pais" => "Samoa", "continente" => "Oceania", "poblacion" =>180000),
        array("id" =>235, "codigo" =>"YEM", "pais" => "Yemen", "continente" => "Asia", "poblacion" =>18112000),
        array("id" =>236, "codigo" =>"YUG", "pais" => "Yugoslavia", "continente" => "Europe", "poblacion" =>10640000),
        array("id" =>237, "codigo" =>"ZAF", "pais" => "South Africa", "continente" => "Africa", "poblacion" =>40377000),
        array("id" =>238, "codigo" =>"ZMB", "pais" => "Zambia", "continente" => "Africa", "poblacion" =>9169000),
        array("id" =>239, "codigo" =>"ZWE", "pais" => "Zimbabwe", "continente" => "Africa", "poblacion" =>11669000)
    ];

}
